### PR TITLE
fix(cli): convert entrypoint to Node for cross-platform support

### LINKED ISSUE #13: CLI doesn't work on Windows
The bin script for the CLI is a bash shell script, which doesn't work on Windows (without users doing things you can't really expect them to do). Can we convert it to a Node script so Sly CLI works cross-platform?

I played around with some solutions and have it working locally by simply pointing bin at `./dist/index.js` directly as I didn't see the need for a TS loader at all, but I also have a version using [`tsx`](https://npm.im/tsx) instead of your custom `ts-loader.js` in case there really is a need to process TS files.

Thoughts? Happy to open a PR if you want.

Thanks.

### PR DESCRIPTION
**Pull request by wKovacs64**
Fixes #13

### CODE REVIEW

**Comment by wKovacs64** [comment]
@jacobparis This change is working for me locally, but I think I'm going to publish my own temporary copy of the CLI to test it "for real" as simulating it with yalc was not as convincing as I'd like.

Let me know if you have any thoughts, though.

**Comment by wKovacs64** [comment]
OK, published my own copy and confirmed it works on Windows and macOS. 👍 

You can try the `@wkovacs64/sly` package yourself if you wish (for the next little while, anyway - I'd like to unpublish it once we're done here).

**Comment by jacobparis** [comment]
Awesome, thank you! I'm adding a test suite and getting the CI stuff set up properly so I stop being a bottleneck to contributions, then I'll merge this

**Comment by halljus** [comment]
Sweet, thanks! Looking forward to a new version being published so I can demo Sly at work (we're stuck on Windows 😢).

**Pull request merged**
